package morseencoder;


import about.personal;
import java.awt.Toolkit;
/**
 * A simple GUI created with the Netbeans GUI designer. The most interesting part is the custom inner enum class 
 * Role which glues the display status of the toggle buttonn proper labels and its corresponding action to be 
 * performed when pushed.
 * 
 * @author Athanasios Kontis
 */
public class MorseFrame extends javax.swing.JFrame {
    
    private enum Role {
        ENCODE ("Switch to Decode", "Plain Text", "Morse Code"),
        DECODE ("Switch to Encode", "Morse Code", "Plain Text");
        private final String desc, mainLabel, dependentLabel;
        Role (String r, String m, String d) {desc = r; mainLabel = m; dependentLabel = d;}
        public String act(String s){
            switch (this) {
                case ENCODE: return Morse.encode(s);
                case DECODE: return Morse.decode(s);
                default: return s;
            }
        }
    }
    
    private Role activeRole = Role.ENCODE;
    
    /**
     * Creates new form MorseFrame
     */
    public MorseFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Ax/pht.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainLabel = new javax.swing.JLabel();
        mainScrollArea = new javax.swing.JScrollPane();
        mainArea = new javax.swing.JTextArea();
        dependentLabel = new javax.swing.JLabel();
        dependentScrollArea = new javax.swing.JScrollPane();
        dependentArea = new javax.swing.JTextArea();
        toggleRolesButton = new javax.swing.JToggleButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Morse Code Encoder/Decoder");
        setBounds(new java.awt.Rectangle(300, 100, 100, 100));
        setResizable(false);

        mainLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mainLabel.setLabelFor(mainScrollArea);
        mainLabel.setText(activeRole.mainLabel);
        mainLabel.setToolTipText("");
        mainLabel.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                mainLabelPropertyChange(evt);
            }
        });

        mainArea.setBackground(new java.awt.Color(204, 204, 204));
        mainArea.setColumns(20);
        mainArea.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        mainArea.setForeground(new java.awt.Color(0, 0, 0));
        mainArea.setLineWrap(true);
        mainArea.setRows(5);
        mainArea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                mainAreaCaretUpdate(evt);
            }
        });
        mainScrollArea.setViewportView(mainArea);

        dependentLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        dependentLabel.setLabelFor(dependentScrollArea);
        dependentLabel.setText(activeRole.dependentLabel);
        dependentLabel.setToolTipText("");

        dependentArea.setEditable(false);
        dependentArea.setBackground(new java.awt.Color(204, 204, 204));
        dependentArea.setColumns(20);
        dependentArea.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        dependentArea.setForeground(new java.awt.Color(0, 0, 0));
        dependentArea.setLineWrap(true);
        dependentArea.setRows(5);
        dependentArea.setAutoscrolls(false);
        dependentScrollArea.setViewportView(dependentArea);

        toggleRolesButton.setBackground(new java.awt.Color(102, 102, 102));
        toggleRolesButton.setFont(new java.awt.Font("Kalpurush", 1, 14)); // NOI18N
        toggleRolesButton.setForeground(new java.awt.Color(255, 255, 255));
        toggleRolesButton.setText(activeRole.desc);
        toggleRolesButton.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                toggleRolesButtonItemStateChanged(evt);
            }
        });

        clearButton.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        exitButton.setText("Close");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dependentLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(clearButton)
                            .addGap(222, 222, 222)
                            .addComponent(exitButton))
                        .addComponent(dependentScrollArea, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(mainScrollArea, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(mainLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toggleRolesButton))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel)
                    .addComponent(toggleRolesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(mainScrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dependentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dependentScrollArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        mainArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void toggleRolesButtonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_toggleRolesButtonItemStateChanged
        activeRole = activeRole == Role.ENCODE ? Role.DECODE : Role.ENCODE;
        mainLabel.setText(activeRole.mainLabel);
        dependentLabel.setText(activeRole.dependentLabel);
        toggleRolesButton.setText(activeRole.desc);
        mainArea.setText(dependentArea.getText().trim());
    }//GEN-LAST:event_toggleRolesButtonItemStateChanged

    private void mainAreaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_mainAreaCaretUpdate
        String encodedText = activeRole.act( mainArea.getText() );
        dependentArea.setText( encodedText );
    }//GEN-LAST:event_mainAreaCaretUpdate

    private void mainLabelPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_mainLabelPropertyChange
        if (evt.getPropertyName().equals("activeRole")) {
            mainLabel.setText(activeRole.mainLabel);
        }
    }//GEN-LAST:event_mainLabelPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MorseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MorseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MorseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MorseFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MorseFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton clearButton;
    javax.swing.JTextArea dependentArea;
    javax.swing.JLabel dependentLabel;
    javax.swing.JScrollPane dependentScrollArea;
    javax.swing.JButton exitButton;
    javax.swing.JTextArea mainArea;
    javax.swing.JLabel mainLabel;
    javax.swing.JScrollPane mainScrollArea;
    javax.swing.JToggleButton toggleRolesButton;
    // End of variables declaration//GEN-END:variables
}
